$font = Fira Code Nerd Font


general {
    disable_loading_bar = false
    hide_cursor = true
    grace = 0
    no_fade_in = false
    no_fade_out = false
}

background {
    monitor = eDP-1
    path = ~/.dotfiles/wallpapers/ichigo.jpeg          
    blur_passes = 3
    blur_size = 7
    noise = 0.0117
    contrast = 0.9
    brightness = 0.65
    vibrancy = 0.18
    vibrancy_darkness = 0.0
}

#hora
label {
    monitor = eDP-1
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = rgba(19, 20, 24, 0.95)
    font_size = 100
    font_family = $font
    position = -60, 100
    halign = right
    valign = bottom
}

label {
    monitor = eDP-1
    text = $USER
    color = rgba(19, 20, 24, 0.95)
    font_size = 50
    font_family = $font
    position = -250, 250
    halign = right
    valign = bottom
}


input-field {
    monitor = eDP-1
    size = 300, 56
    outline_thickness = 3
    dots_size = 0.4
    dots_spacing = 0.3
    dots_center = true
    dots_rounding = -1

    outer_color = rgba(0, 0, 0, 0.5)
    inner_color = rgba(44, 43, 43, 0.5)
    font_color = rgb(235, 217, 217)

    fade_on_empty = true
    hide_input = false

    check_color = rgba(0, 0, 0, 0.5)
    fail_text = <span foreground="##f38ba8">wrong password</span>
    fail_timeout = 1000

    position = 0, -140
    halign = center
    valign = center
}